models/Juegan.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "juegan".
 *
 * @property int $id_juegan
 * @property string|null $dni
 * @property int|null $id_partidos
 *
 * @property Jugadores $dni0
 * @property Partidos $partidos
 */
class Juegan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'juegan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_partidos'], 'integer'],
            [['dni'], 'string', 'max' => 9],
            [['dni', 'id_partidos'], 'unique', 'targetAttribute' => ['dni', 'id_partidos']],
            [['dni'], 'exist', 'skipOnError' => true, 'targetClass' => Jugadores::class, 'targetAttribute' => ['dni' => 'dni']],
            [['id_partidos'], 'exist', 'skipOnError' => true, 'targetClass' => Partidos::class, 'targetAttribute' => ['id_partidos' => 'id_partidos']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_juegan' => 'Id Juegan',
            'dni' => 'Dni',
            'id_partidos' => 'Id Partidos',
        ];
    }

    /**
     * Gets query for [[Dni0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDni0()
    {
        return $this->hasOne(Jugadores::class, ['dni' => 'dni']);
    }

    /**
     * Gets query for [[Partidos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPartidos()
    {
        return $this->hasOne(Partidos::class, ['id_partidos' => 'id_partidos']);
    }
}

controllers/JueganController.php
<?php

namespace app\controllers;

use app\models\Juegan;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Jugadores;
use yii\helpers\ArrayHelper;
use app\models\Partidos;
use Yii;
use app\models\JueganSearch;



/**
 * JueganController implements the CRUD actions for Juegan model.
 */
class JueganController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Juegan models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new JueganSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Juegan model.
     * @param int $id_juegan Id Juegan
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id_juegan)
    {
        return $this->render('view', [
            'model' => $this->findModel($id_juegan),
        ]);
    }

    /**
     * Creates a new Juegan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Juegan();
        $data = ArrayHelper::map(Jugadores::find()->all(), 'dni', 'dni');
        $data1 = ArrayHelper::map(Partidos::find()->all(), 'id_partidos', 'id_partidos');
        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id_juegan' => $model->id_juegan]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'data' => $data,
            'data1' => $data1,
        ]);
    }

    /**
     * Updates an existing Juegan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id_juegan Id Juegan
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id_juegan)
    {
        $model = $this->findModel($id_juegan);
        $data = ArrayHelper::map(Jugadores::find()->all(), 'dni', 'dni');
        $data1 = ArrayHelper::map(Partidos::find()->all(), 'id_partidos', 'id_partidos');

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id_juegan' => $model->id_juegan]);
        }

        return $this->render('update', [
            'model' => $model,
            'data' => $data,
            'data1' => $data1,
        ]);
    }

    /**
     * Deletes an existing Juegan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id_juegan Id Juegan
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id_juegan)
    {
        $this->findModel($id_juegan)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Juegan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id_juegan Id Juegan
     * @return Juegan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id_juegan)
    {
        if (($model = Juegan::findOne(['id_juegan' => $id_juegan])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionInsertarConvocatorias(){
        $model = new Juegan();
        $id_partidos = Yii::$app->request->post('Juegan')['id_partidos'];
        
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // Borra los registros existentes para el ID de partido actual
            Juegan::deleteAll(['id_partidos' => $id_partidos]);

            $jugadoresSeleccionados = Yii::$app->request->post('jugadoresSeleccionados');

            if (!empty($jugadoresSeleccionados)) {
                foreach ($jugadoresSeleccionados as $dni) {
                    $nuevaConvocatoria = new Juegan();
                    $nuevaConvocatoria->id_partidos = $id_partidos;
                    $nuevaConvocatoria->dni = $dni;
                    // Asigna otros atributos del modelo según sea necesario
                    $nuevaConvocatoria->save();
                }
                Yii::$app->session->setFlash('success', 'Convocatoria generada exitosamente.');
                return $this->redirect(['/juegan/convocados', 'codCategoria' => Yii::$app->request->post('codCategoria'), 'id_partidos' => $model->id_partidos]);
            } else {
                Yii::$app->session->setFlash('error', 'Debe seleccionar al menos un jugador.');
                return $this->redirect(['juegan/generarconvocatorias', 'codCategoria' => Yii::$app->request->post('codCategoria'), 'id_partidos' => $model->id_partidos]);
               
            }
        }
        return $this->render('insertar-convocatorias', [
            'model' => $model,
            'id_partidos' => $id_partidos,
        ]);
    }

    public function actionGuardarActualizacion(){
        $model = new Juegan();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // Eliminar jugadores seleccionados existentes
            Juegan::deleteAll(['id_partidos' => $model->id_partidos]);

            // Guardar jugadores seleccionados actualizados
            foreach ($model->jugadoresSeleccionados as $dni) {
                $nuevaConvocatoria = new Juegan();
                $nuevaConvocatoria->id_partidos = $model->id_partidos;
                $nuevaConvocatoria->dni = $dni;
                $nuevaConvocatoria->save();
            }

            return $this->redirect(['/juegan/convocados', 'codCategoria' => Yii::$app->request->post('codCategoria'), 'id_partidos' => $model->id_partidos]);

        }

        // Si la validación o el guardado fallan, vuelve a mostrar la vista de actualización
        return $this->render('actualizar', ['model' => $model]);
    }
    
    public function actionGenerarconvocatorias($codCategoria,$id_partidos){
        $jugadores = new ActiveDataProvider([
            'query' => Jugadores::find()->select("dni, nombre, apellidos, dorsal")->where("cod_categoria = :codCategoria", [':codCategoria' => $codCategoria]),
        ]);
        $convocatoria = Juegan::findOne(['id_partidos' => $id_partidos]);
        if($convocatoria){
             Yii::$app->session->setFlash('error', 'Ya hay una convocatoria creada.');
             return $this->redirect(['/juegan/convocados', 'codCategoria' => $codCategoria, 'id_partidos' => $id_partidos]);
        }else{
            return $this->render("create-convocatoria",[
                "jugadores" => $jugadores,
                "campos" => ['dni, nombre','apellidos','dorsal'],
                "id_partidos" => $id_partidos,
                "codCategoria" => $codCategoria
            ]);
        }
        
    }
    public function actionActualizarconvocatorias($codCategoria,$id_partidos){
        $convocatoria = Juegan::findOne(['id_partidos' => $id_partidos]);

        if (!$convocatoria) {
            Yii::$app->session->setFlash('error', 'Primero debes crear una convocatoria.');
            return $this->redirect(['/juegan/convocados', 'codCategoria' => $codCategoria, 'id_partidos' => $id_partidos]);
        }else{
            $jugadores = new ActiveDataProvider([
                'query' => Jugadores::find()->select("dni ,nombre, apellidos, dorsal")->where("cod_categoria = '$codCategoria'"),
            ]);

            return $this->render("update-convocatoria", [
                "jugadores" => $jugadores,
                "campos" => ['dni, nombre', 'apellidos', 'dorsal'],
                "id_partidos" => $id_partidos,
                "codCategoria" => $codCategoria
            ]);
        }    
    }
    public function actionEliminarconvocatoria($id_partidos, $codCategoria)
    {
        $convocatoria = Juegan::findOne(['id_partidos' => $id_partidos]);

        if (!$convocatoria) {
            Yii::$app->session->setFlash('error', 'No hay convocatoria la convocatoria.');
        } else {
            Juegan::deleteAll(['id_partidos' => $id_partidos]);

            Yii::$app->session->setFlash('success', 'Convocatoria eliminada exitosamente.');
        }

        return $this->redirect(['/juegan/convocados', 'codCategoria' => $id_partidos, 'id_partidos' => $codCategoria]);
    }
    
    public function actionConvocados($codCategoria,$id_partidos){
        
        $convocados = Jugadores::find()
            ->select(['dorsal', 'nombre', 'apellidos','id_partidos'])
            ->join('INNER JOIN', 'juegan', 'juegan.dni = jugadores.dni')
            ->where(['id_partidos' => $id_partidos])
            ->all();
        
        if(empty($convocados) && $codCategoria == null){
            Yii::$app->session->setFlash('error', 'No hay ninguna convocatoria creada para este partido. Debes crear una');
            return $this->render('convocatoria', ['convocados' => $convocados]);
        }

        return $this->render('convocatoria', [
            'convocados' => $convocados,

views/juegan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
/** @var yii\web\View $this */
/** @var app\models\Juegan $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="juegan-form">

    <?php $form = ActiveForm::begin(); ?>

    
<?= $form->field($model, 'dni')->widget(Select2::classname(), [
            'data' => $data,
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]); 
    ?> 

    
<?= $form->field($model, 'id_partidos')->widget(Select2::classname(), [
            'data' => $data1,
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]); 
    ?> 

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/juegan/convocatoria.php
<?php 

use yii\grid\GridView;
use yii\helpers\Html;
?>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?=Html::a('Inicio',['site/index'])?></li>
    <li class="breadcrumb-item"><?=Html::a('Partidos',['site/generarpartidos'])?></li>
    <li class="breadcrumb-item active" aria-current="page">Convocatoria</li>
  </ol>
</nav>
<div class="row centrar pb-4">
    <div class="col-md-10">
        <h1 class="text-center titulo">CONVOCATORIA</h1>
    </div>
</div>
<?= Html::a('Eliminar convocatoria', ['juegan/eliminarconvocatoria',
        'id_partidos' => isset($id_partidos) ? $id_partidos : null,
        'codCategoria' => isset($codCategoria) ? $codCategoria : null
    ], ['class' => 'mb-3 float-right btn btn-danger',
         'data' => [
                'confirm' => 'Estas seguro de que quieres eliminar este elemento',
                'method' => 'post']]) ?>
<?php
echo GridView::widget([
    'dataProvider' => new \yii\data\ArrayDataProvider([
        'allModels' => $convocados,
        'pagination' => false,
    ]),
    'tableOptions' => ['class' => 'table table-bordered table-hover my-gridview '],
    'summary' => '',
    'emptyText' => 'No hay jugadores convocados. Por favor, crea una convocatoria.',
    'columns' => [
        'nombre',
        'apellidos',
        'dorsal',
    ],
]);
?>

<?= Html::a('Crear convocatoria', ['juegan/generarconvocatorias',
    'id_partidos' => isset($id_partidos) ? $id_partidos : null,
    'codCategoria' => isset($codCategoria) ? $codCategoria : null
    ], ['class' => 'float-left btn btn-success mb-5'])?>
        
<?= Html::a('Actualizar convocatoria', ['juegan/actualizarconvocatorias',
    'id_partidos' => isset($id_partidos) ? $id_partidos : null,
    'codCategoria' => isset($codCategoria) ? $codCategoria : null
    ], ['class' => 'float-right btn btn-primary mb-5']) ?>  




    

views/juegan/create-convocatoria.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use app\models\Juegan;
?>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?=Html::a('Inicio',['site/index'])?></li>
    <li class="breadcrumb-item"><?=Html::a('Partidos',['site/generarpartidos'])?></li>
    <li class="breadcrumb-item"><?=Html::a('Convocatoria',['juegan/convocados',
        'id_partidos' => isset($id_partidos) ? $id_partidos : null,
        'codCategoria' => isset($codCategoria) ? $codCategoria : null])?></li>
    <li class="breadcrumb-item active" aria-current="page">Crear convocatoria</li>
  </ol>
</nav>
<div class="row centrar">
    <div class="col-md-10">
        <h1 class="text-center titulo">CREAR CONVOCATORIA</h1>
    </div>
</div>
<?php
$model = new Juegan();
$form = ActiveForm::begin([
    'action' => ['juegan/insertar-convocatorias']
]);
echo Html::hiddenInput('codCategoria', $codCategoria);
echo $form->field($model, 'id_partidos')->hiddenInput(['value' => $id_partidos])->label(false);

echo GridView::widget([
    'dataProvider' => $jugadores,
    'tableOptions' => ['class' => 'table table-bordered table-hover my-gridview '],
    'summary' => '',
    'layout' => "{items}",
    'columns' => [
        [
            'class' => 'yii\grid\CheckboxColumn',
            'name' => 'jugadoresSeleccionados',
            'checkboxOptions' => function ($model) {
                return ['value' => $model->dni];
            },
        ],
        'nombre',
        'apellidos',
        'dorsal'
    ],
]);

echo Html::submitButton('Guardar', ['class' => 'btn btn-primary']);

ActiveForm::end();?>

views/juegan/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Juegan $model */

$this->title = 'Crear Juegan';
$this->params['breadcrumbs'][] = ['label' => 'Juegans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="juegan-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'data' => $data,
        'data1' => $data1,
    ]) ?>

</div>

views/juegan/index.php
<?php

use app\models\Juegan;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Convocatorias';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="juegan-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Crear Juegan', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-bordered table-hover my-gridview '],
        'summary' => '',
        'filterModel' => $searchModel,
        'columns' => [

            'id_juegan',
            'dni',
            'id_partidos',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Juegan $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id_juegan' => $model->id_juegan]);
                 }
            ],
        ],
    ]); ?>


</div>

views/juegan/update-convocatoria.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use app\models\Juegan;
?>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?=Html::a('Inicio',['site/index'])?></li>
    <li class="breadcrumb-item"><?=Html::a('Partidos',['site/generarpartidos'])?></li>
    <li class="breadcrumb-item"><?=Html::a('Convocatoria',['juegan/convocados',
        'id_partidos' => $id_partidos,
        'codCategoria' => $codCategoria])?></li>
    <li class="breadcrumb-item active" aria-current="page">Actualizar convocatoria</li>
  </ol>
</nav>
<div class="row centrar">
    <div class="col-md-10">
        <h1 class="text-center titulo">ACTUALIZAR CONVOCATORIA</h1>
    </div>
</div>
<?php
$model = new Juegan();
$form = ActiveForm::begin([
    'action' => ['juegan/insertar-convocatorias']
]);

echo Html::hiddenInput('codCategoria', $codCategoria);
echo $form->field($model, 'id_partidos')->hiddenInput(['value' => $id_partidos])->label(false);

echo GridView::widget([
    'dataProvider' => $jugadores,
    'tableOptions' => ['class' => 'table table-bordered table-hover my-gridview '],
    'summary' => '',
    'layout' => "{items}",
    'columns' => [
        [
            'class' => 'yii\grid\CheckboxColumn',
            'name' => 'jugadoresSeleccionados',
            'checkboxOptions' => function ($model) {
                return ['value' => $model->dni];
            },
        ],
        'nombre',
        'apellidos',
        'dorsal'
    ],
]);

echo Html::submitButton('Guardar', ['class' => 'btn btn-primary']);

ActiveForm::end();?>

views/juegan/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Juegan $model */

$this->title = 'Actualizar Convocatorias: ' . $model->id_juegan;
$this->params['breadcrumbs'][] = ['label' => 'Convocatorias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_juegan, 'url' => ['view', 'id_juegan' => $model->id_juegan]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="juegan-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'data' => $data,
        'data1' => $data1,
    ]) ?>

</div>

views/juegan/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Juegan $model */

$this->title = $model->id_juegan;
$this->params['breadcrumbs'][] = ['label' => 'convocatoria', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="juegan-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id_juegan' => $model->id_juegan], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Borrar', ['delete', 'id_juegan' => $model->id_juegan], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_juegan',
            'dni',
            'id_partidos',
        ],
    ]) ?>

</div>