controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use app\models\Partidos;
use app\models\Horarioentrenamientos;
use app\models\Jugadores;
use app\models\Preparadores;
use app\models\Categoria;
use yii\data\sqlDataProvider;
use edofre\fullcalendar\models\Event;
use yii\db\Query;
use yii\helpers\Json;
use app\models\NewsForm;
use yii\web\Cookie;
use app\models\Noticias;
use yii\helpers\Html;
use app\models\PartidosSearch;



class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        // Obtener la última noticia desde tu almacenamiento persistente
      $ultimaNoticia = Noticias::find()
        ->orderBy(['id' => SORT_DESC])
        ->limit(3)
        ->all();

      return $this->render('index', [
          'ultimaNoticia' => $ultimaNoticia,
      ]);
    }



    /**
     * Login action.s
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $this->layout = 'main-left'; // Agregar esta línea para establecer el nuevo layout
            return $this->goBack();
        }

        $model->contraseña = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }


    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();
        
        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout() {
        return $this->render('about');
    }

    public function actionInfocategoria() {
        $codCategoriaM = yii:: $app->db->createCommand("select cod_categoria from categoria where cod_categoria LIKE '%M'")->queryAll();
        
        $codCategoriaF = yii:: $app->db->createCommand("select cod_categoria from categoria where cod_categoria LIKE '%F'")->queryAll();
        
        return $this->render('infoCategorias', [
            "codCategoriaM" => $codCategoriaM,  
            "codCategoriaF" => $codCategoriaF,
        ]);
    }
    
    public function actionDatoscategoria($codCategoria){
        $preparadores = yii:: $app->db->createCommand("select nombre, apellidos, telefono, dni from preparadores inner join categoria using(dni) where cod_categoria = '$codCategoria'")->queryAll();
        
        
        $entrenadores = yii:: $app->db->createCommand("select nombre, apellidos, telefono from entrenadores where cod_categoria = '$codCategoria'")->queryAll();
        
        $jugadores = new ActiveDataProvider([
            'query' => Jugadores::find()->select("nombre, apellidos, dorsal")->where("cod_categoria = '$codCategoria'"),
        ]);
               
        return $this->render("datoscategoria",[
            "preparadores" => $preparadores,
            "entrenadores" => $entrenadores,
            "codCategoria" => $codCategoria,
            "jugadores" => $jugadores
        ]);
    }
    
    public function actionMostrarentrenamientos()
    {
        $categorias = [
            'AL_F' => 'Alevín Femenino',
            'AL_M' => 'Alevín Masculino',
            'BN_F' => 'Benjamín Femenino',
            'BN_M' => 'Benjamín Masculino',
            'CAD_F' => 'Cadete Femenino',
            'CAD_M' => 'Cadete Masculino',
            'DH_F' => 'Division de Honor Femenino',
            'DH_M' => 'Division de Honor Masculino',
            'IF_F' => 'Infantil Femenino',
            'IF_M' => 'Infantil Masculino',
            'JUV_F' => 'Juvenil Femenino',
            'JUV_M' => 'Juvenil Masculino',
            'PB_F' => 'Prebenjamín Femenino',
            'PB_M' => 'Prebenjamín Masculino',
            'PRI_F' => 'Primera Femenino',
            'PRI_M' => 'Primera Masculino',
            'SEG_F' => 'Segunda Femenino',
            'SEG_M' => 'Segunda Masculino',
        ];
        $color = [
            'AL_F' => '#FF0000', // Alevín Femenino
            'AL_M' => '#FFCCCC', // Alevín Masculino
            'BN_F' => '#0000FF', // Benjamín Femenino
            'BN_M' => '#CCCCFF', // Benjamín Masculino
            'CAD_F' => '#00FF00', // Cadete Femenino
            'CAD_M' => '#CCFFCC', // Cadete Masculino
            'DH_F' => '#A52A2A', // División de Honor Femenino
            'DH_M' => '#D2B48C', // División de Honor Masculino
            'IF_F' => '#FFFF00', // Infantil Femenino
            'IF_M' => '#FFFFCC', // Infantil Masculino
            'JUV_F' => '#FFA500', // Juvenil Femenino
            'JUV_M' => '#FFDAB9', // Juvenil Masculino
            'PB_F' => '#00FFFF', // Prebenjamín Femenino
            'PB_M' => '#E0FFFF', // Prebenjamín Masculino
            'PRI_F' => '#800080', // Primera Femenino
            'PRI_M' => '#E6E6FA', // Primera Masculino
            'SEG_F' => '#FFC0CB', // Segunda Femenino
            'SEG_M' => '#FFE6F1', // Segunda Masculino
        ];

        
        $query = (new Query())
            ->select(['id_partidos','cod_categoria', 'fecha', 'hora', 'competicion', 'contrincante'])
            ->from('partidos')
            ->all();
        
        $formattedEvents = [];
        foreach ($query as $row) {
            $start = $row['fecha'] . ' ' . $row['hora'];
            $id = 'sadas' .';'. $row['id_partidos'] .';'. 'Fecha: ' . date('d-m-Y', strtotime($row['fecha'])) . "<br>Hora: " . date('H:i', strtotime($row['hora'])) . "<br>Competicion: " . $row['competicion'] . "<br>Contrincante: " . $row['contrincante'];
            $codCategoria = $row['cod_categoria'];
            $nombreCategoria = isset($categorias[$codCategoria]) ? $categorias[$codCategoria] : $codCategoria;
            
            $formattedEvents[] = new Event([
                'title' => $nombreCategoria,
                'start' => date('Y-m-d H:i', strtotime($start)),
                'id' => $id,
                'backgroundColor' => $color[$codCategoria], // Asigna el color rojo al fondo del evento
                'borderColor' => $color[$codCategoria], // Asigna el color rojo al borde del evento
            ]);
        }
        
        $dayMappings = [
            0 => 'Sunday',     // Domingo
            1 => 'Monday',     // Lunes
            2 => 'Tuesday',    // Martes
            3 => 'Wednesday',  // Miércoles
            4 => 'Thursday',   // Jueves
            5 => 'Friday',     // Viernes
            6 => 'Saturday',   // Sábado
        ];
        $dayMapping = [
            0 => 'Domingo',     // Domingo
            1 => 'Lunes',     // Lunes
            2 => 'Martes',    // Martes
            3 => 'Miércoles',  // Miércoles
            4 => 'Jueves',   // Jueves
            5 => 'Viernes',     // Viernes
            6 => 'Sábado',   // Sábado
        ];
        
        $entrenamientos = Yii::$app->db->createCommand("SELECT diasemana, hinicio, hfinal, cod_categoria FROM horarioentrenamientos")->queryAll();

        foreach ($entrenamientos as $entrenamiento) {
            $diasemana = $entrenamiento['diasemana'];
            $inicio = $entrenamiento['hinicio'];
            $fin = $entrenamiento['hfinal'];

            $startDate = date('Y-m-d', strtotime('next ' . $dayMappings[$diasemana]));
            $endDate = date('Y-m-d', strtotime('+1 year', strtotime($startDate)));

            $currentDate = $startDate;
            while (strtotime($currentDate) <= strtotime($endDate)) {
                
                $event = new Event([
                    'title' => $categorias[$entrenamiento['cod_categoria']],
                    'id' => 'entrenamiento' . ';'. $entrenamiento['cod_categoria'] .';'. $dayMapping[$diasemana],
                    'start' => $currentDate . ' ' . $inicio,
                    'end' => $currentDate . ' ' . $fin,
                    'backgroundColor' => $color[$codCategoria], // Asigna el color rojo al fondo del evento
                    'borderColor' => $color[$codCategoria], // Asigna el color rojo al borde del evento
                ]);
                
                $formattedEvents[] = $event;
                

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'Nuestro Club';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row centrar pb-4">
    <div class="col-md-10">
        <h1 class="text-center titulo">HISTORIA DEL SARDINERO H.C.</h1>
    </div>
</div>
<!DOCTYPE html>
<html>
<head>
    <title>Historia del Sardinero H.C.</title>
</head>
<body>
    <div class="float-left">
         <?= Html::img('@web/img/historia1.jpg', ['alt' => Yii::$app->name]) ?>
    </div>
    <div class="float-right">
        <?= Html::img('@web/img/historia2.jpg', ['alt' => Yii::$app->name]) ?>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<p>En el año 1984, un grupo de amigos, apasionados por el hockey hierba, funda el Sardinero H.C. Inicialmente su estructura es la de un club de hockey masculino formado por jugadores juveniles e infantiles de la “cantera” del Colegio Calasanz y procedentes de La Pasiega H.C.</p>
<p>Es en la temporada 1987/88, cuando se crea la sección de hockey femenino, convirtiéndose en parte importante de la historia de nuestro club. Un equipo, que llegó a ser subcampeón de la Copa de la Reina y que, además, consiguió jugar la Recopa de Europa, quedando en 5º lugar.</p>
<p>Posteriormente en la temporada 1992/93, se logra un acuerdo de patrocinio con Caja Cantabria, pasándose a denominar Caja Cantabria Sardinero, vigente hasta el año 2012 en el que finalizó dicho convenio.</p>
<p>Desde el principio el Sardinero H.C. ha contado con equipos de todas las categorías tanto masculina como femenina (benjamines, alevines, infantiles, juveniles y absoluta). Actualmente, la Escuela de Hockey, formada por más de 200 jóvenes de edades comprendidas entre los 5 y 15 años, está dirigida por Oscar Barrena y Alejandro Siri, en colaboración con el Instituto Municipal de Deportes. El número de equipos federados tanto en categorías inferiores como seniors suma un total de 30, lo que hace que para la temporada 2017-2018 tengamos más de 400 jugadores federados. ¡Quién lo iba a decir 34 años después!</p>
<p>Nuestras categorías inferiores, equipos infantiles, cadetes y juveniles, tanto masculinos como femeninos, han participado a lo largo de la historia del Club en múltiples Campeonatos de España y fases de sector en las modalidades de hierba y sala, consiguiendo grandes resultados deportivos, así como medallas en las fases finales.</p>
<p>Además, durante toda su historia el Sardinero H.C., ha sido, es y será un gran dinamizador del hockey hierba tanto a nivel regional como nacional.</p>
<p>Hemos organizado numerosos sectores y fases finales de Campeonatos de España en las categorías masculina y femenina tanto en sala como en hierba. De igual manera, hemos organizado dos fases finales de la Copa de la Reina y colaborado con la Federación Cántabra de Hockey y la Federación Española de Hockey en torneos internacionales de prestigio, como por ejemplo, el Campeonato de Europa de hockey sala en el año 2004 o el Torneo Preolímpico 3 Naciones celebrado en Santander en el año 2012 o el Campeonato de Europa Sub-18 que se celebrará este año 2018 en Santander, entre otros.</p>
<p>Desde el año 1982 el Calasanz H.C., y posteriormente el Sardinero H.C., organizamos el Memorial Carlos Cagigal, en recuerdo de un jugador juvenil fallecido en accidente. Un torneo que se ha convertido en referencia dentro del ámbito del hockey y que tradicionalmente ha reunido a los mejores equipos nacionales e internacionales. Este año se ha celebrado la XXXVII edición de este Torneo en el que han participado equipos nacionales y extranjeros, tanto en categoría masculina como femenina.</p>
<p>Asimismo, se organiza a finales de temporada el Torneo Sardinero en el que participan los equipos de la cantera del club (desde prebenjamines hasta infantiles). Un torneo que ya va por su 14ª edición y que reúne cada año, a más de 550 jugadores procedentes de diferentes equipos nacionales e internacionales.</p>
<p>Pero además de la labor formativa y dinamizadora, hemos aportado jugadores internacionales en todas las categorías (sub-16, sub-18, sub-21 y absolutas) tanto masculinas como femeninas en las modalidades de hierba y sala. Muchos de estos jugadores han participado en campeonatos europeos, mundiales, Champions Trophy o Juegos Olímpicos, consiguiendo importantes triunfos mientras vestían la camiseta de nuestro Club.</p>
<p>Técnicos y jefes de equipo del Sardinero H.C. han formado parte de las diferentes selecciones nacionales de hierba y sala: Pablo Galán, Angel Laso, Alejandro Siri, Bernardino Herrera, Antonio González o Mar Feito, lo mismo que los árbitros internacionales Belén González, Ana Fernández y Carlos Rodríguez.</p>
<p>De nuestro Club, han salido directivos con cargos relevantes en la Federaciones Española y Europea (José Manuel Trueba, Pablo Galán, etc.).</p>
<p>Lo que empezó siendo un club familiar, a día de hoy, se ha convertido en una entidad deportiva con una estructura consolidada, que cuenta con tres equipos en categoría nacional (División de Honor B masculina, Primera División masculina y Primera División femenina).</p>
<p>Con el paso de los años, nuestro club se ha convertido en parte importante del hockey español en todos los estamentos, tanto deportivo, como técnico y ejecutivo.</p>
<p>La historia del Sardinero HC, nuestro club, irá ligada siempre al esfuerzo, al trabajo y al espíritu de lucha. Tres premisas con las que trabajamos día a día y con las que hemos conseguido consolidar esta pequeña gran familia que se ha convertido en un clásico dentro del hockey español.</p>
</body>
</html>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contacto';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <div class="row centrar pb-4">
        <div class="col-md-10">
            <h1 class="text-center titulo">CONTACTO</h1>
        </div>
    </div>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Gracias por contactar con el Sardinero Hc. Responderemos lo antes posible.
        </div>

    <?php else: ?>


        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'nombre')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'titulo') ?>

                    <?= $form->field($model, 'informacion')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'codigo')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Enviar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/convocatoria.php
<?php 

use yii\grid\GridView;
use yii\helpers\Html;

?>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?=Html::a('Inicio',['site/index'])?></li>
    <li class="breadcrumb-item"><?=Html::a('Eventos',['site/mostrarentrenamientos'])?></li>
    <li class="breadcrumb-item active" aria-current="page">Convocatoria</li>
  </ol>
</nav>
<div class="row centrar pb-4">
    <div class="col-md-10">
        <h1 class="text-center titulo">CONVOCATORIA</h1>
    </div>
</div>
<?php
echo GridView::widget([
    'dataProvider' => new \yii\data\ArrayDataProvider([
        'allModels' => $convocados,
        'pagination' => false,
    ]),
    'tableOptions' => ['class' => 'table table-bordered table-hover my-gridview '],
    'summary' => '',
    'emptyText' => 'No hay jugadores convocados. Por favor, crea una convocatoria.',
    'columns' => [
        'nombre',
        'apellidos',
        'dorsal',
    ],
]);
?>

views/site/datoscategoria.php
<?php
    use yii\grid\GridView;
    use yii\widgets\Breadcrumbs;
    use yii\helpers\Html;
    $categorias = [
            'AL_F' => 'Alevín Femenino',
            'AL_M' => 'Alevín Masculino',
            'BN_F' => 'Benjamín Femenino',
            'BN_M' => 'Benjamín Masculino',
            'CAD_F' => 'Cadete Femenino',
            'CAD_M' => 'Cadete Masculino',
            'DH_F' => 'Division de Honor Femenino',
            'DH_M' => 'Division de Honor Masculino',
            'IF_F' => 'Infantil Femenino',
            'IF_M' => 'Infantil Masculino',
            'JUV_F' => 'Juvenil Femenino',
            'JUV_M' => 'Juvenil Masculino',
            'PB_F' => 'Prebenjamín Femenino',
            'PB_M' => 'Prebenjamín Masculino',
            'PRI_F' => 'Primera Femenino',
            'PRI_M' => 'Primera Masculino',
            'SEG_F' => 'Segunda Femenino',
            'SEG_M' => 'Segunda Masculino',
        ];
?>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?=Html::a('Inicio',['site/index'])?></li>
    <li class="breadcrumb-item"><?=Html::a('Categorias',['site/infocategoria'])?></li>
    <li class="breadcrumb-item active" aria-current="page"><?= $categorias[$codCategoria] ?></li>
  </ol>
</nav>
<div class="row centrar pb-4">
    <div class="col-md-10">
        <h1 class="text-center titulo"><?= $categorias[$codCategoria] ?></h1>
    </div>
</div>
        <?php 

    $cont = 0;
    foreach($preparadores as $key => $dato){
        $nombreP[] = ($dato['nombre']);
        $apellidosP[] = ($dato['apellidos']);
        $telefonoP[] = ($dato['telefono']);
                        
        echo"<div class='col-md-6 mx-auto'>
                <div class='card alturaminima border border-dark'>
                    <div class='card-body tarjeta'>".
                        "<h3 class='tituloEquipo'>Preparador Fisico</h3>                  
                        <p> Nombre: ".$nombreP[$cont]."<br>
                        Apellidos: ".$apellidosP[$cont]."<br>
                        Telefono: <a href='tel:" . $telefonoP[$cont] . "'>" . $telefonoP[$cont] . "</a></p>                   
                    </div>
                </div>
            </div>";
    }
?>
<div class="body-content">
    <div class="row">
<?php
    foreach ($entrenadores as $key => $dato) {
        $nombreE[] = ($dato['nombre']);
        $apellidosE[] = ($dato['apellidos']);
        $telefonoE[] = ($dato['telefono']);

        echo"<div class='col-md-6'>
                <div class='card alturaminima border border-dark'>
                    <div class='card-body tarjeta'>" .
                        "<h3 class='tituloEquipo'>Entrenador</h3>
                        <p> Nombre: " . $nombreE[$cont] . "<br>
                        Apellidos: " . $apellidosE[$cont] . "<br>
                        Telefono: <a href='tel:" . $telefonoE[$cont] . "'>" . $telefonoE[$cont] . "</a></p>
                    </div>
                </div>
            </div>";
        $cont++;
    }
?>
    </div>
</div>    

<div class="pt-3">
    <?=
        GridView::widget([
                    'dataProvider' => $jugadores,
                    'tableOptions' => ['class' => 'table table-bordered table-hover my-gridview '],
                    'summary' => '',
                    'layout' => "{items}",
                    'columns' => ['nombre','apellidos','dorsal']
        ]);
    ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;

?>
<div class="row centrar pb-2">
    <div class="col-md-10">
        <h1 class="text-center titulo2">SARDINERO HC<?= Html::img('@web/img/sardinero.png', ['alt' => Yii::$app->name, 'class' => 'pl-3 pt-3']) ?></h1>
    </div>
</div>
<div class="centrar">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
             <?= Html::img('@web/img/c1.jpg', ['alt' => Yii::$app->name]) ?>
          </div>
          <div class="carousel-item">
             <?= Html::img('@web/img/c2.jpg', ['alt' => Yii::$app->name]) ?>
          </div>
          <div class="carousel-item">
            <?= Html::img('@web/img/c3.jpg', ['alt' => Yii::$app->name]) ?>
          </div>
        </div>
    </div>
</div>

<div class="pt-5 pb-3">
    <div class="container">
        <div class="row">
            <div class="pl-5 pr-5">
                <!-- Contenido del primer componente -->
                <div class="d-flex flex-column justify-content-center align-items-center">
                    <?= Html::img('@web/img/02-Unicaja-Banco-Vertical-300x279.jpg', ['alt' => Yii::$app->name]) ?>
                    <?= Html::img('@web/img/cantabria-deporte-300x101.jpg', ['alt' => Yii::$app->name, 'class' => ' pt-2']) ?>
                    <?= Html::img('@web/img/jubilar-rgb-horizontal-300x141.jpg', ['alt' => Yii::$app->name, 'class' => ' pt-2']) ?>
                    <?= Html::img('@web/img/iberdrola-300x139.png', ['alt' => Yii::$app->name, 'class' => ' pt-2']) ?>                    
                </div>
            </div>
            <div class="noticias">
                <!-- Contenido del segundo componente -->
                <body data-spy="scroll" data-target="#navbar-example">
                    <div class="container">
                        <div class="row">
                            <div class="mx-auto">
                                <nav id="navbar-example" class="navbar noticias-custom rounded">
                                    <a class="navbar-brand notias-titulo">Noticias</a>
                                    <ul class="nav nav-pills">
                                        <?php foreach ($ultimaNoticia as $index => $noticia): ?>
                                            <li class="nav-item">
                                                <a class="nav-link btn btn-outline-light" href="#section<?= $index + 1 ?>"><?= Html::encode($noticia->titulo) ?></a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </nav>

                                <div class="scrollspy-example">
                                    <?php foreach ($ultimaNoticia as $index => $noticia): ?>
                                        <h4 id="section<?= $index + 1 ?>"><?= Html::encode($noticia->titulo) ?></h4>
                                        <p><?= nl2br(Html::encode($noticia->contenido)) ?></p>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </body>
            </div>
        </div>
    </div>
</div>

views/site/infoCategorias.php
<?php
use yii\helpers\Html;
use yii\widgets\ListView;
/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */
 $cont = 0;
 $categorias = [
            'AL_F' => 'Alevín Femenino',
            'AL_M' => 'Alevín Masculino',
            'BN_F' => 'Benjamín Femenino',
            'BN_M' => 'Benjamín Masculino',
            'CAD_F' => 'Cadete Femenino',
            'CAD_M' => 'Cadete Masculino',
            'DH_F' => 'Division de Honor Femenino',
            'DH_M' => 'Division de Honor Masculino',
            'IF_F' => 'Infantil Femenino',
            'IF_M' => 'Infantil Masculino',
            'JUV_F' => 'Juvenil Femenino',
            'JUV_M' => 'Juvenil Masculino',
            'PB_F' => 'Prebenjamín Femenino',
            'PB_M' => 'Prebenjamín Masculino',
            'PRI_F' => 'Primera Femenino',
            'PRI_M' => 'Primera Masculino',
            'SEG_F' => 'Segunda Femenino',
            'SEG_M' => 'Segunda Masculino',
        ];
?>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><?=Html::a('Inicio',['site/index'])?></li>
    <li class="breadcrumb-item active" aria-current="page">Categorias</li>
  </ol>
</nav>
<div class="row centrar">
    <div class="col-md-10">
        <h1 class="text-center titulo">INFORMACIÓN CATEGORÍAS</h1>
    </div>
</div>
<div class="body-content">
    <div class="row">
        <?php foreach($codCategoriaM as $key => $dato){
            $femenino[]=($codCategoriaF[$key]['cod_categoria']);
            $masculino[]=($dato['cod_categoria']);
            
            echo"<div class='col-md-6'>
                <div class='card alturaminima border border-dark'>
                    <div class='card-body tarjeta'>".
                        "<h3 class='tituloEquipo'>".$categorias[$masculino[$cont]]."</h3>".
                        "<p>".$masculino[$cont]."</p>".
                        "<p>".
                            Html::a('Datos de la categoría', ['site/datoscategoria', 'codCategoria' => $masculino[$cont]], ['class' => 'btn btn-dark']) 
                        ."</p>".
                    "</div>
                 </div>
            </div>".
            
            "<div class='col-md-6'>
                <div class='card alturaminima border border-dark'>
                    <div class='card-body tarjeta'>".
                        "<h3 class='tituloEquipo'>".$categorias[$femenino[$cont]]."</h3>".
                        "<p>".$femenino[$cont]."</p>".
                        "<p>".
                            Html::a('Datos de la categoría', ['site/datoscategoria', 'codCategoria' => $femenino[$cont]], ['class' => 'btn btn-dark']) 
                        ."</p>".
                    "</div>
                 </div>
            </div>";
            $cont++;
        }    
        ?>
    </div>
</div>